media:
  input: static/uploads
  output: /uploads

content:
  # Blog posts
  - name: prace
    label: Prace
    type: collection
    path: content/prace
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      primary: title
      sort: date
      order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: date
        label: Publish Date
        type: date
        required: true

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: description
        label: Description
        type: text

      - name: tags
        label: Tags
        type: string
        list: true

      - name: categories
        label: Categories
        type: string
        list: true

      - name: featured_image
        label: Featured Image
        type: image

      - name: keywords
        label: Keywords
        type: string

      - name: body
        label: Content
        type: rich-text

  # Static pages
  - name: pages
    label: Pages
    type: collection
    path: content
    format: yaml-frontmatter
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true

      - name: keywords
        label: Keywords
        type: string

      - name: draft
        label: Draft
        type: boolean
        default: false

      - name: body
        label: Content
        type: rich-text

    - name: pages
        label: Pages
        type: collection
        path: content
        format: yaml-frontmatter
        filename: "{primary}.md"
        fields:
          - name: title
            label: Title
            type: string
            required: true
    
          - name: keywords
            label: Keywords
            type: string
    
          - name: draft
            label: Draft
            type: boolean
            default: false
    
          - name: body
            label: Content
            type: rich-text
    
      

settings:
  hide_git_history: false